name: "Lokalise File Download"

on:
  workflow_dispatch:
    inputs:
      token: # id of input
        description: "Your CLI/API token for Lokalise"
        required: true
      project-id: # id of input
        description: "Your project ID for Lokalise"
        required: true
      file-path: # id of input
        description: "The path to the destination folder"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download file from Lokalise
        run: |
         chmod +x ./scripts/download.sh
         ./scripts/download.sh
        shell: bash
        env:
          LOKALISE_TOKEN: ${{ inputs.token }}
          LOKALISE_PROJECT_ID: ${{ inputs.project-id }}
          TRANSLATION_FILE: ${{ inputs.file-path }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          draft: false
          title: 'Lokalise: Translations update'
          add-paths: |
            ${{ inputs.file-path }}
          labels: |
            lokalise
          body: |
            Update translation
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request